s = {1, 2, 3, 4, 5}
print(s)
a = int(input("enter num to add : "))
s.add(a)
print("after adding element")
print(s)
b = int(input("enter num to delete : "))
s.remove(b)
print("after deleting an element")
print(s)
